startswith_cs – AoC-2024
startswith_cs Function
5 statements
Source File
private pure function startswith_cs(str, substring)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: str
type(string), intent(in) :: substring
Return Value logical
Calls
Called by
Source Code
    pure logical function startswith_cs(str, substring)
        character(len=*),intent(in) :: str
        type(string),intent(in) :: substring
        startswith_cs = startswith(str, substring%str)
    end function startswith_cs
Call graph
startswith_cs calls startswith
startswith calls startswith_cs, startswith_cc, startswith_sc, startswith_ss
startswith_sc calls startswith
startswith_ss calls startswith