startswith_ss – AoC-2024
startswith_ss Function
4 statements
Source File
private pure function startswith_ss(str, substring)
Arguments
Type Intent Optional Attributes Name
type(string), intent(in) :: str
type(string), intent(in) :: substring
Return Value logical
Calls
Called by
Source Code
    pure logical function startswith_ss(str, substring)
        type(string),intent(in) :: str, substring
        startswith_ss = startswith(str%str, substring%str)
    end function startswith_ss
Call graph
startswith_ss calls startswith
startswith calls startswith_ss, startswith_cc, startswith_cs, startswith_sc
startswith_cs calls startswith
startswith_sc calls startswith