swap_str – AoC-2024
swap_str Subroutine
8 statements
Source File
private pure elemental subroutine swap_str(i1, i2)
Swap two character string values
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(inout) :: i1
character(len=*), intent(inout) :: i2
Called by
Source Code
    pure elemental subroutine swap_str(i1,i2)
    character(len=*),intent(inout) :: i1
    character(len=*),intent(inout) :: i2
    character(len=len(i1)) :: tmp
    tmp = i1
    i1  = i2
    i2  = tmp
    end subroutine swap_str
Call graph
swap calls swap_str
sort_ascending calls swap
sort calls sort_ascending
unique32 calls sort
unique64 calls sort
unique calls unique32, unique64